trigger:
- master

jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'
  timeoutInMinutes: 90
  steps:
  - checkout: self
    submodules: true
  - script: |
      sudo apt-get update
      DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
        cmake libgmp-dev libmpfr-dev libmpc-dev \
        libboost-all-dev bison texinfo \
        ruby flex curl
    displayName: 'Install prerequisites'
  - script: |
      mkdir build
      cd build
      ../build-toolchain.bash
    displayName: 'Build'
  - script: |
      cd build
      curl -L -O https://github.com/autc04/executor/releases/download/v0.1.0/Executor2000-0.1.0-Linux.tar.bz2
      tar xfvj Executor2000-0.1.0-Linux.tar.bz2 Executor2000-0.1.0-Linux/bin/executor-headless
      echo "executor-path=`pwd`/Executor2000-0.1.0-Linux/bin/executor-headless" > ~/.LaunchAPPL.cfg
      echo "emulator=executor" >> ~/.LaunchAPPL.cfg
      ctest --no-compress-output -T test -E Carbon || true
    displayName: Run Tests using Executor 2000
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'CTest'
      testResultsFiles: build/Testing/**/*.xml
      buildPlatform: 'x86_64-linux'

